# Used https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml as example
package:
  name: resicled
  version: "0.1.0"

source:
  # Note for future: https://conda-forge.org/docs/maintainer/adding_pkgs.html#tarballs-no-repos
  git_rev: main
  git_url: https://gricad-gitlab.univ-grenoble-alpes.fr/green-scop/activity-browser.git

build:
  noarch: python
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt"
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python >=3.8,<3.10
    - brightway2 >=2.4.2

about:
  home: https://gricad-gitlab.univ-grenoble-alpes.fr/green-scop/activity-browser.git
  license: LGPL3+
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Plugin for Activity Browser
  description: |
    Evaluating the recyclability of electr(on)ic product for improving product design
    (eco-oriented design end of life).
    This package can be used as a plugin for Activity Browser or directly with Brightway2
    using the ReSICLED API.
