import os

class Fixture():
    def __init__(self):
         self.db_material = self.get_db_material()
         self.db_directive = self.get_db_directive()
         self.db_guidelines = self.get_db_guidelines()
         
    def get_db_material(self):
        self.material = {
            ("resicled_material", "1"):{
                "id_material": 1,
                "type_material": "Polymers",
                "name_material": "ABS",
                "recdis_material": "94,00",
                "enerdis_material": "1,00",
                "wastedis_material": "5,00",
                "recshr_material": "74,00",
                "enershr_material": "1,00",
                "wasteshr_material": "25,00",
                "price_material": 200,
                "pollutant_material": "false"
                }, 
            ("resicled_material", "2"):{
                "id_material": 2,
                "type_material": "Polymers",
                "name_material": "ABS with any additives",
                "recdis_material": "94,00",
                "enerdis_material": "1,00",
                "wastedis_material": "5,00",
                "recshr_material": "0,00",
                "enershr_material": "5,00",
                "wasteshr_material": "95,00",
                "price_material": 400,
                "pollutant_material": "false"
                }, 
            ("resicled_material", "3"):{
                "id_material": 3,
                "type_material": "Polymers",
                "name_material": "HIPS",
                "recdis_material": "94,00",
                "enerdis_material": "1,00",
                "wastedis_material": "5,00",
                "recshr_material": "83,00",
                "enershr_material": "1,00",
                "wasteshr_material": "16,00",
                "price_material": 545,
                "pollutant_material": "false"
                }, 
            ("resicled_material", "4"):{
                "id_material": 4,
                "type_material": "Polymers",
                "name_material": "HIPS with any additives",
                "recdis_material": "94,00",
                "enerdis_material": "1,00",
                "wastedis_material": "5,00",
                "recshr_material": "0,00",
                "enershr_material": "5,00",
                "wasteshr_material": "95,00",
                "price_material": 281,
                "pollutant_material": "false"
                }, 
            ("resicled_material", "5"):{
                "id_material": 5,
                "type_material": "Polymers",
                "name_material": "PP",
                "recdis_material": "94,00",
                "enerdis_material": "1,00",
                "wastedis_material": "5,00",
                "recshr_material": "90,00",
                "enershr_material": "1,00",
                "wasteshr_material": "9,00",
                "price_material": 330,
                "pollutant_material": "false"
                }, 
            ("resicled_material", "6"):{
                "id_material": 6,
                "type_material": "Polymers",
                "name_material": "PP+EPDM",
                "recdis_material": "94,00",
                "enerdis_material": "1,00",
                "wastedis_material": "5,00",
                "recshr_material": "90,00",
                "enershr_material": "1,00",
                "wasteshr_material": "9,00",
                "price_material": 315,
                "pollutant_material": "false"
                }, 
            ("resicled_material", "7"):{
                "id_material": 7,
                "type_material": "Polymers",
                "name_material": "PP-GF",
                "recdis_material": "94,00",
                "enerdis_material": "1,00",
                "wastedis_material": "5,00",
                "recshr_material": "90,00",
                "enershr_material": "1,00",
                "wasteshr_material": "9,00",
                "price_material": 300,
                "pollutant_material": "false"
                }, 
            ("resicled_material", "8"):{
                "id_material": 8,
                "type_material": "Polymers",
                "name_material": "PP with any other additives",
                "recdis_material": "94,00",
                "enerdis_material": "1,00",
                "wastedis_material": "5,00",
                "recshr_material": "0,00",
                "enershr_material": "5,00",
                "wasteshr_material": "95,00",
                "price_material": 181,
                "pollutant_material": "false"
                }, 
            ("resicled_material", "9"):{
                "id_material": 9,
                "type_material": "Polymers",
                "name_material": "P/E",
                "recdis_material": "94,00",
                "enerdis_material": "1,00",
                "wastedis_material": "5,00",
                "recshr_material": "90,00",
                "enershr_material": "1,00",
                "wasteshr_material": "9,00",
                "price_material": 200,
                "pollutant_material": "false"
                }, 
            ("resicled_material", "10"):{
                "id_material": 10,
                "type_material": "Polymers",
                "name_material": "PC",
                "recdis_material": "94,00",
                "enerdis_material": "1,00",
                "wastedis_material": "5,00",
                "recshr_material": "0,00",
                "enershr_material": "5,00",
                "wasteshr_material": "95,00",
                "price_material": 248,
                "pollutant_material": "false"
                }, 
            ("resicled_material", "11"):{
                "id_material": 11,
                "type_material": "Polymers",
                "name_material": "ABS-PC",
                "recdis_material": "94,00",
                "enerdis_material": "1,00",
                "wastedis_material": "5,00",
                "recshr_material": "0,00",
                "enershr_material": "5,00",
                "wasteshr_material": "95,00",
                "price_material": 530,
                "pollutant_material": "false"
                }, 
            ("resicled_material", "12"):{
                "id_material": 12,
                "type_material": "Polymers",
                "name_material": "PA",
                "recdis_material": "94,00",
                "enerdis_material": "1,00",
                "wastedis_material": "5,00",
                "recshr_material": "0,00",
                "enershr_material": "5,00",
                "wasteshr_material": "95,00",
                "price_material": 29928,
                "pollutant_material": "false"
                }, 
            ("resicled_material", "13"):{
                "id_material": 13,
                "type_material": "Polymers",
                "name_material": "PA-6",
                "recdis_material": "94,00",
                "enerdis_material": "1,00",
                "wastedis_material": "5,00",
                "recshr_material": "0,00",
                "enershr_material": "5,00",
                "wasteshr_material": "95,00",
                "price_material": 15000,
                "pollutant_material": "false"
                }, 
            ("resicled_material", "14"):{
                "id_material": 14,
                "type_material": "Polymers",
                "name_material": "HDPE",
                "recdis_material": "94,00",
                "enerdis_material": "1,00",
                "wastedis_material": "5,00",
                "recshr_material": "0,00",
                "enershr_material": "5,00",
                "wasteshr_material": "95,00",
                "price_material": 132,
                "pollutant_material": "false"
                }, 
            ("resicled_material", "15"):{
                "id_material": 15,
                "type_material": "Polymers",
                "name_material": "SAN",
                "recdis_material": "94,00",
                "enerdis_material": "1,00",
                "wastedis_material": "5,00",
                "recshr_material": "0,00",
                "enershr_material": "5,00",
                "wasteshr_material": "95,00",
                "price_material": 793,
                "pollutant_material": "false"
                }, 
            ("resicled_material", "16"):{
                "id_material": 16,
                "type_material": "Polymers",
                "name_material": "SAN without additive",
                "recdis_material": "94,00",
                "enerdis_material": "1,00",
                "wastedis_material": "5,00",
                "recshr_material": "0,00",
                "enershr_material": "5,00",
                "wasteshr_material": "95,00",
                "price_material": 396,
                "pollutant_material": "false"
                }, 
            ("resicled_material", "17"):{
                "id_material": 17,
                "type_material": "Polymers",
                "name_material": "PE-Film, PS-E (packaging)",
                "recdis_material": "15,00",
                "enerdis_material": "14,00",
                "wastedis_material": "71,00",
                "recshr_material": "0,00",
                "enershr_material": "0,00",
                "wasteshr_material": "100,00",
                "price_material": "",
                "pollutant_material": "false"
                }, 
            ("resicled_material", "18"):{
                "id_material": 18,
                "type_material": "Polymers",
                "name_material": "Other Polymer",
                "recdis_material": "0,00",
                "enerdis_material": "5,00",
                "wastedis_material": "95,00",
                "recshr_material": "0,00",
                "enershr_material": "5,00",
                "wasteshr_material": "95,00",
                "price_material": 400,
                "pollutant_material": "false"
                }, 
            ("resicled_material", "19"):{
                "id_material": 19,
                "type_material": "Metals",
                "name_material": "Steel",
                "recdis_material": "95,00",
                "enerdis_material": "0,00",
                "wastedis_material": "5,00",
                "recshr_material": "95,00",
                "enershr_material": "0,00",
                "wasteshr_material": "5,00",
                "price_material": 176,
                "pollutant_material": "false"
                }, 
            ("resicled_material", "20"):{
                "id_material": 20,
                "type_material": "Metals",
                "name_material": "Aluminium",
                "recdis_material": "93,00",
                "enerdis_material": "0,00",
                "wastedis_material": "7,00",
                "recshr_material": "91,00",
                "enershr_material": "0,00",
                "wasteshr_material": "9,00",
                "price_material": 370,
                "pollutant_material": "false"
                }, 
            ("resicled_material", "21"):{
                "id_material": 21,
                "type_material": "Metals",
                "name_material": "Copper",
                "recdis_material": "95,00",
                "enerdis_material": "0,00",
                "wastedis_material": "5,00",
                "recshr_material": "85,00",
                "enershr_material": "0,00",
                "wasteshr_material": "15,00",
                "price_material": 2447,
                "pollutant_material": "false"
                }, 
            ("resicled_material", "22"):{
                "id_material": 22,
                "type_material": "Metals",
                "name_material": "Metal alloys",
                "recdis_material": "80,00",
                "enerdis_material": "0,00",
                "wastedis_material": "20,00",
                "recshr_material": "70,00",
                "enershr_material": "0,00",
                "wasteshr_material": "30,00",
                "price_material": 800,
                "pollutant_material": "false"
                }, 
            ("resicled_material", "23"):{
                "id_material": 23,
                "type_material": "Metals",
                "name_material": "Other metal",
                "recdis_material": "80,00",
                "enerdis_material": "0,00",
                "wastedis_material": "20,00",
                "recshr_material": "70,00",
                "enershr_material": "0,00",
                "wasteshr_material": "30,00",
                "price_material": 900,
                "pollutant_material": "false"
                }, 
            ("resicled_material", "24"):{
                "id_material": 24,
                "type_material": "Other",
                "name_material": "LCD",
                "recdis_material": "0,00",
                "enerdis_material": "0,00",
                "wastedis_material": "100,00",
                "recshr_material": "0,00",
                "enershr_material": "0,00",
                "wasteshr_material": "0,00",
                "price_material": "",
                "pollutant_material": "true"
                }, 
            ("resicled_material", "25"):{
                "id_material": 25,
                "type_material": "Other",
                "name_material": "Cable (high current)",
                "recdis_material": "33,00",
                "enerdis_material": "0,00",
                "wastedis_material": "67,00",
                "recshr_material": "0,00",
                "enershr_material": "0,00",
                "wasteshr_material": "0,00",
                "price_material": "",
                "pollutant_material": "true"
                }, 
            ("resicled_material", "26"):{
                "id_material": 26,
                "type_material": "Other",
                "name_material": "Cable (low current)",
                "recdis_material": "24,00",
                "enerdis_material": "0,00",
                "wastedis_material": "76,00",
                "recshr_material": "0,00",
                "enershr_material": "0,00",
                "wasteshr_material": "0,00",
                "price_material": "",
                "pollutant_material": "true"
                }, 
            ("resicled_material", "27"):{
                "id_material": 27,
                "type_material": "Other",
                "name_material": "Battery (Lead-acid)",
                "recdis_material": "60,00",
                "enerdis_material": "0,00",
                "wastedis_material": "40,00",
                "recshr_material": "0,00",
                "enershr_material": "0,00",
                "wasteshr_material": "0,00",
                "price_material": "",
                "pollutant_material": "true"
                }, 
            ("resicled_material", "28"):{
                "id_material": 28,
                "type_material": "Other",
                "name_material": "Battery (Ni-Cd) (2 type: portable (<1kg); non-portable (>1kg))",
                "recdis_material": "70,00",
                "enerdis_material": "0,00",
                "wastedis_material": "30,00",
                "recshr_material": "0,00",
                "enershr_material": "0,00",
                "wasteshr_material": "0,00",
                "price_material": "",
                "pollutant_material": "true"
                }, 
            ("resicled_material", "29"):{
                "id_material": 29,
                "type_material": "Other",
                "name_material": "Other battery",
                "recdis_material": "45,00",
                "enerdis_material": "0,00",
                "wastedis_material": "55,00",
                "recshr_material": "0,00",
                "enershr_material": "0,00",
                "wasteshr_material": "0,00",
                "price_material": "",
                "pollutant_material": "true"
                }, 
            ("resicled_material", "30"):{
                "id_material": 30,
                "type_material": "Other",
                "name_material": "CPT",
                "recdis_material": "90,00",
                "enerdis_material": "0,00",
                "wastedis_material": "10,00",
                "recshr_material": "0,00",
                "enershr_material": "0,00",
                "wasteshr_material": "0,00",
                "price_material": "",
                "pollutant_material": "true"
                }, 
            ("resicled_material", "31"):{
                "id_material": 31,
                "type_material": "Other",
                "name_material": "Moteur",
                "recdis_material": "85,40",
                "enerdis_material": "0,13",
                "wastedis_material": "14,47",
                "recshr_material": "81,00",
                "enershr_material": "0,00",
                "wasteshr_material": "19,00",
                "price_material": "",
                "pollutant_material": "false"
                }, 
            ("resicled_material", "32"):{
                "id_material": 32,
                "type_material": "Other",
                "name_material": "Heatsink",
                "recdis_material": "93,00",
                "enerdis_material": "0,00",
                "wastedis_material": "7,00",
                "recshr_material": "0,00",
                "enershr_material": "0,00",
                "wasteshr_material": "100,00",
                "price_material": "",
                "pollutant_material": "false"
                }, 
            ("resicled_material", "33"):{
                "id_material": 33,
                "type_material": "Other",
                "name_material": "Cable (optical)",
                "recdis_material": "0,00",
                "enerdis_material": "0,00",
                "wastedis_material": "100,00",
                "recshr_material": "0,00",
                "enershr_material": "0,00",
                "wasteshr_material": "0,00",
                "price_material": "",
                "pollutant_material": "true"
                }, 
            ("resicled_material", "34"):{
                "id_material": 34,
                "type_material": "Other",
                "name_material": "Bulb",
                "recdis_material": "0,00",
                "enerdis_material": "0,00",
                "wastedis_material": "100,00",
                "recshr_material": "0,00",
                "enershr_material": "0,00",
                "wasteshr_material": "0,00",
                "price_material": "",
                "pollutant_material": "true"
                }, 
            ("resicled_material", "35"):{
                "id_material": 35,
                "type_material": "Other",
                "name_material": "Cartouche encre",
                "recdis_material": "0,00",
                "enerdis_material": "0,00",
                "wastedis_material": "100,00",
                "recshr_material": "0,00",
                "enershr_material": "0,00",
                "wasteshr_material": "0,00",
                "price_material": "",
                "pollutant_material": "true"
                }, 
            ("resicled_material", "36"):{
                "id_material": 36,
                "type_material": "Other",
                "name_material": "Cardboard (packaging)",
                "recdis_material": "59,00",
                "enerdis_material": "7,00",
                "wastedis_material": "34,00",
                "recshr_material": "0,00",
                "enershr_material": "0,00",
                "wasteshr_material": "100,00",
                "price_material": "",
                "pollutant_material": "false"
                }, 
            ("resicled_material", "37"):{
                "id_material": 37,
                "type_material": "Other",
                "name_material": "PWB (Rich)",
                "recdis_material": "18,00",
                "enerdis_material": "43,00",
                "wastedis_material": "39,50",
                "recshr_material": "0,00",
                "enershr_material": "0,00",
                "wasteshr_material": "0,00",
                "price_material": "",
                "pollutant_material": "true"
                }
            }
        return self.material
    
    def get_db_directive(self):
        self.directive = {
            ("resicled_directive", "1"): {
                "directive_number": 1,
                "directive_title": "Large household appliances",
                "directive_comment": "-   Large cooling appliances\n-   Refrigerators\n-   Freezers\n-   Other large appliances used for refrigeration, conservation and\n  storage of food\n-   Washing machines\n-   Clothes dryers\n-   Dish washing machines\n-   Cooking\n-   Electric stoves\n-   Electric hot plates\n-   Microwaves\n-   Other large aplliances used for cooking and other processing of \n  food\n-   Electric heating appliances\n-   Electric radiators\n-   Other large appliances for heating roms, beds, seating fourniture\n-   Electric fans\n-   Air conditioner appliances\n-   Other fanning, exhaust ventilation and conditioning equipment\naze",
                "dismantling_recycling_rate": 0.75,
                "dismantling_recovery_rate": 0.8,
                "dismantling_residual_waste_rate": 0.2,
                "shredding_recycling_rate": 0.75,
                "shredding_recovery_rate": 0.8,
                "shredding_residual_waste_rate": 0.2,
                "mixed_recycling_rate": 0.75,
                "mixed_recovery_rate": 0.8,
                "mixed_residual_waste_rate": 0.2,
            },
            ("resicled_directive", "2"): {
                "directive_number": 2,
                "directive_title": "Small household appliances",
                "directive_comment": "-   Vacuum cleaners\n-   Carpet sweepers\n-   Other appliances for cleaning\n-   Appliances used for sewing, knitting, weaving and other \n  processing for textiles\n-   Irons and other appliances for ironing, magling and other care of\n  clothing\n-   Toaster\n-   Fryers\n-   Grinders, coffee machines and equipment for opening or sealing\n  containers or packages\n-   Electric knives\n-   Appliances for hair-cutting, hair drying, tooth brushing, shaving\n  massage and other body care appliances\n-   Clocks, watches and equipment for the purpose of measuring, \nindicating or registering time\n-   Scales",
                "dismantling_recycling_rate": 0.5,
                "dismantling_recovery_rate": 0.7,
                "dismantling_residual_waste_rate": 0.3,
                "shredding_recycling_rate": 0.5,
                "shredding_recovery_rate": 0.7,
                "shredding_residual_waste_rate": 0.3,
                "mixed_recycling_rate": 0.5,
                "mixed_recovery_rate": 0.7,
                "mixed_residual_waste_rate": 0.3,
            },
            ("resicled_directive", "3"): {
                "directive_number": 3,
                "directive_title": "IT and telecommunication equipement",
                "directive_comment": "-   Centralised data processing:\n     *  Mainframes\n     *  Minicomputers\n     *  Printer units\n-   Personal computing:\n     *   Personal computers (CPU, mouse, screen and keyboard included)\n     *   Laptot computers (CPU, mouse, screen and keyboard included)\n     *   Notebook computers\n     *   Notepad computers\n     *   Printers\n     *   Copying equipment\n     *   Electrical and electronic typewriters\n     *   Pocket and desk calculators\n     *   and other products and equipment for the collection, storage,\n      processing, presentation or communication of information by\n      electronic means\n-   User terminals and systems\n-   Facsimile\n-   Telex\n-   Telephones\n-   Pay telephones\n-   Cordless telephones\n-   Cellular telephones\n-   Answering systems\n-   and other products or equipment of trnsmitting sound, imagines or\n  other information by telecommunications",
                "dismantling_recycling_rate": 0.65,
                "dismantling_recovery_rate": 0.75,
                "dismantling_residual_waste_rate": 0.25,
                "shredding_recycling_rate": 0.65,
                "shredding_recovery_rate": 0.75,
                "shredding_residual_waste_rate": 0.25,
                "mixed_recycling_rate": 0.65,
                "mixed_recovery_rate": 0.75,
                "mixed_residual_waste_rate": 0.25,
            },
            ("resicled_directive", "4"): {
                "directive_number": 4,
                "directive_title": "Consumer equipment",
                "directive_comment": "-   Radio sets\n-   Television sets\n-   Videocameras\n-   Video recorders\n-   Hi-fi recorders\n-   Audio amplifiers\n-   Musical instruments\n-   And other products or equipment for the purpose of recording or\n  reproducing sound or images, including signals or other tecnologies\n  for the distribution of sound and image than by telecommunications",
                "dismantling_recycling_rate": 0.65,
                "dismantling_recovery_rate": 0.75,
                "dismantling_residual_waste_rate": 0.25,
                "shredding_recycling_rate": 0.65,
                "shredding_recovery_rate": 0.75,
                "shredding_residual_waste_rate": 0.25,
                "mixed_recycling_rate": 0.65,
                "mixed_recovery_rate": 0.75,
                "mixed_residual_waste_rate": 0.25,
            },
            ("resicled_directive", "51"): {
                "directive_number": 51,
                "directive_title": "Lighting equipment - Gas discharge lamps",
                "directive_comment": "Gas discharge lamps -   Luminaires for fluorescent lamps with the exception of luminaires in\n  households\n-   Straight fluorescenct lamps\n-   Compact fluorescent lamps\n-   High intensity discharge lamps, including pressure sodium lamps and\n  metal halide lamps\n-   Low pressure sodium lamps\n-   Other ligthing or equipment for the purpose of spreading or\n  controlling light with the exception of filament bulbs",
                "dismantling_recycling_rate": 0.8,
                "dismantling_recovery_rate": 0.8,
                "dismantling_residual_waste_rate": 0.2,
                "shredding_recycling_rate": 0.8,
                "shredding_recovery_rate": 0.8,
                "shredding_residual_waste_rate": 0.2,
                "mixed_recycling_rate": 0.8,
                "mixed_recovery_rate": 0.8,
                "mixed_residual_waste_rate": 0.2,
            },
            ("resicled_directive", "52"): {
                "directive_number": 52,
                "directive_title": "Lighting equipment - Other",
                "directive_comment": "Other -   Luminaires for fluorescent lamps with the exception of luminaires in\n  households\n-   Straight fluorescenct lamps\n-   Compact fluorescent lamps\n-   High intensity discharge lamps, including pressure sodium lamps and\n  metal halide lamps\n-   Low pressure sodium lamps\n-   Other ligthing or equipment for the purpose of spreading or\n  controlling light with the exception of filament bulbs",
                "dismantling_recycling_rate": 0.5,
                "dismantling_recovery_rate": 0.7,
                "dismantling_residual_waste_rate": 0.3,
                "shredding_recycling_rate": 0.5,
                "shredding_recovery_rate": 0.7,
                "shredding_residual_waste_rate": 0.3,
                "mixed_recycling_rate": 0.5,
                "mixed_recovery_rate": 0.7,
                "mixed_residual_waste_rate": 0.3,
            },
            ("resicled_directive", "6"): {
                "directive_number": 6,
                "directive_title": "Electrical and electronic tools (with the exception of large-scale stationary industrial tools)",
                "directive_comment": "-   Drills\n-   Saws\n-   Sewing machines\n-   Equipment for turning, milling, sanding, grinding, sawing, cutting,\n  shearing, drilling, making holes, punching, folding, bending or similar\n  processing of wood, metal and other materials\n-   Tools for riveting, nailing or screwing or removing rivets, nails, \n  screws or similar uses\n-   Tools for welding, soldering or similar use\n-   Equipment for spraying, spreading, dispersing or other treatment of\n  liquid or gaseous substances by other means\n-   Tools for mowing or other gardening activities",
                "dismantling_recycling_rate": 0.5,
                "dismantling_recovery_rate": 0.7,
                "dismantling_residual_waste_rate": 0.3,
                "shredding_recycling_rate": 0.5,
                "shredding_recovery_rate": 0.7,
                "shredding_residual_waste_rate": 0.3,
                "mixed_recycling_rate": 0.5,
                "mixed_recovery_rate": 0.7,
                "mixed_residual_waste_rate": 0.3,
            },
            ("resicled_directive", "7"): {
                "directive_number": 7,
                "directive_title": "Toys, leisure and sports equiment",
                "directive_comment": "-   Electric trains or car racing sets\n-   Hand-held video games consoles\n-   Video games\n-   Computer for biking, diving, running, rowing, etc.\n-   Sports equipment with electric or electronic components\n-   Coin slot machines",
                "dismantling_recycling_rate": 0.5,
                "dismantling_recovery_rate": 0.7,
                "dismantling_residual_waste_rate": 0.3,
                "shredding_recycling_rate": 0.5,
                "shredding_recovery_rate": 0.7,
                "shredding_residual_waste_rate": 0.3,
                "mixed_recycling_rate": 0.5,
                "mixed_recovery_rate": 0.7,
                "mixed_residual_waste_rate": 0.3,
            },
            ("resicled_directive", "8"): {
                "directive_number": 8,
                "directive_title": "Medical devices (with the exception of all implanted and infected products)",
                "directive_comment": "-   Radiotherapy equipment\n-   Cardiology\n-   Dyalisis\n-   Pulmonary ventilators\n-   Nuclear medicine\n-   Laboratory equipment for in-vitro diagnosis\n-   Analysers\n-   Freezers\n-   Fertilization tests\n-   Other appliances for detecting, preventing, monitoring, treating,\n  alleviating illness, injury or disability",
                "dismantling_recycling_rate": 0,
                "dismantling_recovery_rate": 0,
                "dismantling_residual_waste_rate": 1,
                "shredding_recycling_rate": 0,
                "shredding_recovery_rate": 0,
                "shredding_residual_waste_rate": 1,
                "mixed_recycling_rate": 0,
                "mixed_recovery_rate": 0,
                "mixed_residual_waste_rate": 1,
            },
            ("resicled_directive", "9"): {
                "directive_number": 9,
                "directive_title": "Monitoring and control instruments",
                "directive_comment": "-   Smoke detector\n-   Heating regulators\n-   Thermostats\n-   Measuring, weighing or adjusting appliances for households or as\n  laboratory equipment\n-   Other monitoring and control instruments used in industrial \n  installations (e. g. in control panels)",
                "dismantling_recycling_rate": 0.5,
                "dismantling_recovery_rate": 0.7,
                "dismantling_residual_waste_rate": 0.3,
                "shredding_recycling_rate": 0.5,
                "shredding_recovery_rate": 0.7,
                "shredding_residual_waste_rate": 0.3,
                "mixed_recycling_rate": 0.5,
                "mixed_recovery_rate": 0.7,
                "mixed_residual_waste_rate": 0.3,
            },
            ("resicled_directive", "10"): {
                "directive_number": 10,
                "directive_title": "Automatic dispensers",
                "directive_comment": "-   Automatic dispensers for hot drinks\n-   Automatic dispensers for hot or cold bottles or cans\n-   Automatic dispensers for solid products\n-   Automatic dispensers for money\n-   All appliances which deliver automatically all kind of products",
                "dismantling_recycling_rate": 0.75,
                "dismantling_recovery_rate": 0.8,
                "dismantling_residual_waste_rate": 0.2,
                "shredding_recycling_rate": 0.75,
                "shredding_recovery_rate": 0.8,
                "shredding_residual_waste_rate": 0.2,
                "mixed_recycling_rate": 0.75,
                "mixed_recovery_rate": 0.8,
                "mixed_residual_waste_rate": 0.2,
            },
            ("resicled_directive", "11"): {
                "directive_number": 11,
                "directive_title": "No comparison with categories",
                "directive_comment": "",
                "dismantling_recycling_rate": 0,
                "dismantling_recovery_rate": 0,
                "dismantling_residual_waste_rate": 0,
                "shredding_recycling_rate": 0,
                "shredding_recovery_rate": 0,
                "shredding_residual_waste_rate": 0,
                "mixed_recycling_rate": 0,
                "mixed_recovery_rate": 0,
                "mixed_residual_waste_rate": 0,
            },
        }
        return self.directive 
    
    def get_db_guidelines(self):
        self.guidelines = {
            ("resicled_guidelines","1") : {
                "guideline_number": 1,
                "guideline_name": "Minimise number of different types of materials (including additives for polymers and alloys for metals)",
                "recovery_strategy": "RAD&RAS",
                "design_parameters": "Material / composant / substance",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","2") :{
                "guideline_number": 2,
                "guideline_name": "If possible (if size and shape of part allows it), mark plastic and metal parts according to ISO 11469",
                "recovery_strategy": "Recycle / recover after dismantling (RAD)",
                "design_parameters": "Material / composant / substance",
                "assembly_position": "All",
                "part_type": "P&M"
            },
            ("resicled_guidelines","3") :{
                "guideline_number": 3,
                "guideline_name": "\"Think of other marking technologies for parts (e.g. bar codes, colour, chemical \"\"traceur\"\", etc.)\"",
                "recovery_strategy": "RAD&RAS",
                "design_parameters": "Material / composant / substance",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","4") :{
                "guideline_number": 4,
                "guideline_name": "Use recycled materials",
                "recovery_strategy": "RAD&RAS",
                "design_parameters": "Material / composant / substance",
                "assembly_position": "All",
                "part_type": "Polymer"
            },
            ("resicled_guidelines","5") :{
                "guideline_number": 5,
                "guideline_name": "Use the most recyclable materials",
                "recovery_strategy": "RAD&RAS",
                "design_parameters": "Material / composant / substance",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","6") :{
                "guideline_number": 6,
                "guideline_name": "Avoid sticks and metal inserts on plastic parts",
                "recovery_strategy": "Recycle / recover after dismantling (RAD)",
                "design_parameters": "All",
                "assembly_position": "All",
                "part_type": "Polymer"
            },
            ("resicled_guidelines","7") :{
                "guideline_number": 7,
                "guideline_name": "If a charge is to be added to a polymer, verify with recycler that te charge does not hinder the recycling activity",
                "recovery_strategy": "RAD&RAS",
                "design_parameters": "Material / composant / substance",
                "assembly_position": "All",
                "part_type": "Polymer"
            },
            ("resicled_guidelines","8") :{
                "guideline_number": 8,
                "guideline_name": "If different types of polymers have to be closely associated, prefer types of plastics that could be easely separated after shredding ",
                "recovery_strategy": "Recycle / recover after shredding (RAS)",
                "design_parameters": "Material / composant / substance",
                "assembly_position": "All",
                "part_type": "Polymer"
            },
            ("resicled_guidelines","9") :{
                "guideline_number": 9,
                "guideline_name": "If different types of polymers or of metals have to be closely associated, and if they are not separable, prefer types of polymers or of metals that are compatible",
                "recovery_strategy": "Recycle / recover after shredding (RAS)",
                "design_parameters": "Material / composant / substance",
                "assembly_position": "All",
                "part_type": "P&M"
            },
            ("resicled_guidelines","10") :{
                "guideline_number": 10,
                "guideline_name": "Design metallic parts and assemblies so that the liberation of pure material particles during shredding is facilitated",
                "recovery_strategy": "Recycle / recover after shredding (RAS)",
                "design_parameters": "All",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","11") :{
                "guideline_number": 11,
                "guideline_name": "Prefer clear colour to dark colour",
                "recovery_strategy": "RAD&RAS",
                "design_parameters": "Material / composant / substance",
                "assembly_position": "All",
                "part_type": "Polymer"
            },
            ("resicled_guidelines","12") :{
                "guideline_number": 12,
                "guideline_name": "Use inoffensive materials when incinerated",
                "recovery_strategy": "Energy recovery",
                "design_parameters": "Material / composant / substance",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","13") :{
                "guideline_number": 13,
                "guideline_name": "Minimise number of fasteners",
                "recovery_strategy": "Recycle / recover after dismantling (RAD)",
                "design_parameters": "Links",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","14") :{
                "guideline_number": 14,
                "guideline_name": "Minimise number of types of fasteners / number of tools",
                "recovery_strategy": "Recycle / recover after dismantling (RAD)",
                "design_parameters": "Links",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","15") :{
                "guideline_number": 15,
                "guideline_name": "Prefer fasteners easy to remove",
                "recovery_strategy": "D&RAD",
                "design_parameters": "Links",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","16") :{
                "guideline_number": 16,
                "guideline_name": "Make sure that fasteners that will have to be unlocked are easely accessible / visible",
                "recovery_strategy": "D&RAD",
                "design_parameters": "L&A",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","17") :{
                "guideline_number": 17,
                "guideline_name": "Think of fasteners that can be broken instead of dismantled",
                "recovery_strategy": "D&RAD",
                "design_parameters": "Links",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","18") :{
                "guideline_number": 18,
                "guideline_name": "Minimise number of parts",
                "recovery_strategy": "Recycle / recover after dismantling (RAD)",
                "design_parameters": "All",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","19") :{
                "guideline_number": 19,
                "guideline_name": "Focus on a limited number of parts whose caracteristics (mass, material, position, etc.) bring good recyclability performances",
                "recovery_strategy": "Recycle / recover after shredding (RAS)",
                "design_parameters": "All",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","20") :{
                "guideline_number": 20,
                "guideline_name": "Make design modular",
                "recovery_strategy": "Re-use / remanufacture / repair",
                "design_parameters": "Architecture",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","21") :{
                "guideline_number": 21,
                "guideline_name": "Make high value parts easely accessible",
                "recovery_strategy": "Recycle / recover after dismantling (RAD)",
                "design_parameters": "Architecture",
                "assembly_position": "Deep",
                "part_type": "All"
            },
            ("resicled_guidelines","22") :{
                "guideline_number": 22,
                "guideline_name": "Reduce the number / the weight of pollutants",
                "recovery_strategy": "Depollution",
                "design_parameters": "Material / composant / substance",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","23") :{
                "guideline_number": 23,
                "guideline_name": "Make pollutant (battery, fluids, some PWB, CRT, etc.) easely accessible and clearly marked",
                "recovery_strategy": "Depollution",
                "design_parameters": "Architecture",
                "assembly_position": "Deep",
                "part_type": "All"
            },
            ("resicled_guidelines","24") :{
                "guideline_number": 24,
                "guideline_name": "Put pollutants in the same location",
                "recovery_strategy": "Depollution",
                "design_parameters": "Architecture",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","25") :{
                "guideline_number": 25,
                "guideline_name": "Make draining points for fluids accessible and visible ",
                "recovery_strategy": "Depollution",
                "design_parameters": "Architecture",
                "assembly_position": "Superficial",
                "part_type": "All"
            },
            ("resicled_guidelines","26") :{
                "guideline_number": 26,
                "guideline_name": "Think of uniforming disassembly direction",
                "recovery_strategy": "D&RAD",
                "design_parameters": "Architecture",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","27") :{
                "guideline_number": 27,
                "guideline_name": "Design products for stability during disassembly",
                "recovery_strategy": "D&RAD",
                "design_parameters": "Architecture",
                "assembly_position": "Superficial",
                "part_type": "All"
            },
            ("resicled_guidelines","28") :{
                "guideline_number": 28,
                "guideline_name": "Think of central unlocking mechanism ",
                "recovery_strategy": "Recycle / recover after dismantling (RAD)",
                "design_parameters": "L&A",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","29") :{
                "guideline_number": 29,
                "guideline_name": "Think of Disassembly Embedded Design solutions where triggered  elements turns disassembly easy",
                "recovery_strategy": "D&RAD",
                "design_parameters": "M&L",
                "assembly_position": "Superficial",
                "part_type": "All"
            },
            ("resicled_guidelines","30") :{
                "guideline_number": 30,
                "guideline_name": "Think of Disassembly Embedded Design solutions where material with sufficient thermal expansion coefficient are chosen for snap-fits",
                "recovery_strategy": "D&RAD",
                "design_parameters": "M&L",
                "assembly_position": "Superficial",
                "part_type": "All"
            },
            ("resicled_guidelines","31") :{
                "guideline_number": 31,
                "guideline_name": "Think of Active Disassembly techniques where all fasteners can be activated by external triggers",
                "recovery_strategy": "D&RAD",
                "design_parameters": "M&L",
                "assembly_position": "Superficial",
                "part_type": "All"
            },
            ("resicled_guidelines","32") :{
                "guideline_number": 32,
                "guideline_name": "Promote longer life for products (through product quality, repairability, etc.)  especially for products with most disgnificant impact out of use phase",
                "recovery_strategy": "Reduce",
                "design_parameters": "All",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","33") :{
                "guideline_number": 33,
                "guideline_name": "Think of repairability/remanucturability of product",
                "recovery_strategy": "Re-use / remanufacture / repair",
                "design_parameters": "All",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","34") :{
                "guideline_number": 34,
                "guideline_name": "Think of re-use of parts",
                "recovery_strategy": "Re-use / remanufacture / repair",
                "design_parameters": "All",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","35") :{
                "guideline_number": 35,
                "guideline_name": "Think of overdimensioning some parts so that it is possible to machine them during remanufacturing process.",
                "recovery_strategy": "Re-use / remanufacture / repair",
                "design_parameters": "All",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","36") :{
                "guideline_number": 36,
                "guideline_name": "Use standards parts as far as possible",
                "recovery_strategy": "Re-use / remanufacture / repair",
                "design_parameters": "All",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","37") :{
                "guideline_number": 37,
                "guideline_name": "Minimise weight of the product",
                "recovery_strategy": "All",
                "design_parameters": "All",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","38") :{
                "guideline_number": 38,
                "guideline_name": "Use renewable materials (ex: natural fibers)",
                "recovery_strategy": "Energy recovery",
                "design_parameters": "Material / composant / substance",
                "assembly_position": "All",
                "part_type": "Polymer"
            },
            ("resicled_guidelines","39") :{
                "guideline_number": 39,
                "guideline_name": "\"Think of filling-in a \"\"recycling profile\"\" (or end-of-life treatment manual)  for the product to be communicated to treatment facilities\"",
                "recovery_strategy": "Depollution",
                "design_parameters": "All",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","40") :{
                "guideline_number": 40,
                "guideline_name": "Think of mentioning procedures to be followed at end-of-life in the technical leaflet of the product",
                "recovery_strategy": "All",
                "design_parameters": "All",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","41") :{
                "guideline_number": 41,
                "guideline_name": "Think of safety of treatment operators: beware of mechanical components that store mechanical energy (i.e. springs)",
                "recovery_strategy": "D&RAD",
                "design_parameters": "Architecture",
                "assembly_position": "All",
                "part_type": "All"
            },
            ("resicled_guidelines","42") :{
                "guideline_number": 42,
                "guideline_name": "Think of marking the product as covered by WEEE Directive",
                "recovery_strategy": "All",
                "design_parameters": "Architecture",
                "assembly_position": "Superficial",
                "part_type": "All"
            },
            ("resicled_guidelines","43") :{
                "guideline_number": 43,
                "guideline_name": "Avoid coating (e.g. painting, varnish) on metallic parts",
                "recovery_strategy": "RAD&RAS",
                "design_parameters": "All",
                "assembly_position": "All",
                "part_type": "Metal"
            },
            ("resicled_guidelines","44") :{
                "guideline_number": 44,
                "guideline_name": "Avoid coating (metal, plastic film, paiting, textile, film, etc.) on plastics parts",
                "recovery_strategy": "RAD&RAS",
                "design_parameters": "All",
                "assembly_position": "All",
                "part_type": "Polymer"
            }

        }
        return self.guidelines
